apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
    - "q2hydaks-otpv2h27.hcp.westus.azmk8s.io"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
