apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
    #Note: The '{AKS_FQDN}' token will be substituted with the actual DNS label of the ingress controller's public IP by github workflow.
    - q2hyd-bvc6cta9bac8gkgy.b01.azurefd.net
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
